name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

jobs:

  release:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

      - name: Releaser configuration
        run: |
          echo '{
                   "tagFormat":"v${version}",
                   "plugins": [
                      [
                        "@semantic-release/commit-analyzer",
                        {
                          "preset": "angular",
                          "releaseRules": [
                            {"type": "refactor", "release": "patch"},
                            {"type": "chore", "release": "patch"}
                          ]
                        }
                      ],
                      "@semantic-release/release-notes-generator",
                      [
                        "@semantic-release/changelog",
                        {
                          "changelogFile": "CHANGELOG.md"
                        }
                      ],
                      [
                        "@semantic-release/git",
                        {
                          "assets": ["CHANGELOG.md"],
                          "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
                        }
                      ],
                      "@semantic-release/github"
                   ]
                }
          '> .releaserc

      - name: Release
        id: release
        uses: cycjimmy/semantic-release-action@5982a02995853159735cb838992248c4f0f16166 # v2
        with:
          semantic_version: 17.4.7
          branches: |
            [
              'main'
            ]
          extra_plugins: |
            @semantic-release/commit-analyzer@8.0.1
            @semantic-release/release-notes-generator@9.0.3
            @semantic-release/changelog@5.0.1
            @semantic-release/git@9.0.1
            @semantic-release/github@7.2.3
        env:
          GIT_CREDENTIALS: git:${{ secrets.PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
